
name: built_vector
version: 0.1.0
description: Generate Flutter vector code from SVG-like files.
homepage: https://github.com/aloisdeniel/built_vector

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  xml: ^6.0.1
  source_gen: ^1.2.2
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  path_parsing: ^1.0.0
  args: ^2.3.1
  recase: ^4.0.0